### ISSUE TITLE
/footer/blogmessage 接口 空指针异常

### ISSUE THREAD

**Issue by photowey** [oneStarLR/myblog-mybatis#1]
重现步骤：
1.初始化数据库数据结构（未初始化数据）
2.直接启动项目
报错如下：
```java
java.lang.NullPointerException: null
	at com.star.controller.IndexController.blogMessage(IndexController.java:95)
```
异常分析:
接口：com.star.service.Impl.BlogServiceImpl#getBlogViewTotal
返回的数据为NULL（如下图）,但是 在IndexController.java:95 将其拆箱为int基础类型，于是出现了空指针。
建议: 判断返回结果，当返回为NULL的时候，赋值0。
![image](https://user-images.githubusercontent.com/24807449/87617852-eadbc480-c74a-11ea-9922-a8a1ec9a0ee2.png)

**Comment by oneStarLR** [comment]
很感谢你的提出，这里当数据为空时会出现空指针异常，我已经做出了修改，目前还没有提交，我是直接修改的SQL语句，当返回数据为NULL时赋值为0，感谢你的建议！
[cid:image001.png@01D65B59.F175E260]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: photowey<mailto:notifications@github.com>
发送时间: 2020年7月16日 10:02
收件人: oneStarLR/myblog-mybatis<mailto:myblog-mybatis@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [oneStarLR/myblog-mybatis] /footer/blogmessage 接口 空指针异常 (#1)


重现步骤：
1.初始化数据库数据结构（未初始化数据）
2.直接启动项目
报错如下：

java.lang.NullPointerException: null



        at com.star.controller.IndexController.blogMessage(IndexController.java:95)

异常分析:
接口：com.star.service.Impl.BlogServiceImpl#getBlogViewTotal
返回的数据为NULL（如下图）,但是 在IndexController.java:95 将其拆箱为int基础类型，于是出现了空指针。
建议: 判断返回结果，当返回为NULL的时候，赋值0。
[image]<https://user-images.githubusercontent.com/24807449/87617852-eadbc480-c74a-11ea-9922-a8a1ec9a0ee2.png>

―
