### ISSUE TITLE
/types/{id} 接口数组下标越界异常

### ISSUE THREAD

**Issue by photowey** [oneStarLR/myblog-mybatis#2]
重现步骤：
1.初始化数据库数据结构（未初始化数据）
2.直接启动项目
报错如下：
```java
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.star.controller.TypeShowController.types(TypeShowController.java:41)
```
异常分析: 
1.首页点击分类进入
2.由于我本地为初始化数据( 相当于测试环节的边界测试 )
3.查询出来的 types 列表长度( size() ) == 0
4.这个时候，由于该请求来自于首页（id == -1）,于是执行 com.star.controller.TypeShowController#types 的
41行 代码  types.get(0)，就会抛出该异常。
建议: 判断 types 为空列表的场景。
![image](https://user-images.githubusercontent.com/24807449/87627724-ee2e7a80-c761-11ea-8f1f-439163b5be09.png)

**Comment by oneStarLR** [comment]
感谢提出！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: photowey<mailto:notifications@github.com>
发送时间: 2020年7月16日 12:48
收件人: oneStarLR/myblog-mybatis<mailto:myblog-mybatis@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [oneStarLR/myblog-mybatis] /types/{id} 接口数组下标越界异常 (#2)


重现步骤：
1.初始化数据库数据结构（未初始化数据）
2.直接启动项目
报错如下：

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0



        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)



        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)



        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)



        at java.base/java.util.Objects.checkIndex(Objects.java:372)



        at java.base/java.util.ArrayList.get(ArrayList.java:458)



        at com.star.controller.TypeShowController.types(TypeShowController.java:41)

异常分析:
1.首页点击分类进入
2.由于我本地为初始化数据( 相当于测试环节的边界测试 )
3.查询出来的 types 列表长度( size() ) == 0
4.这个时候，由于该请求来自于首页（id == -1）,于是执行 com.star.controller.TypeShowController#types 的
41行 代码 types.get(0)，就会抛出该异常。
建议: 判断 types 为空列表的场景。
[image]<https://user-images.githubusercontent.com/24807449/87627724-ee2e7a80-c761-11ea-8f1f-439163b5be09.png>

―
